image_size: 224
mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]

# Resize strategy
resize_mode: random_resized_crop
rrc_scale_min: 0.7
rrc_scale_max: 1.0

# Augmentations (train only)
horizontal_flip_p: 0.5
random_brightness_contrast_p: 0.3
shift_scale_rotate_p: 0.5
shift_limit: 0.0625
scale_limit: 0.1
rotate_limit: 15
hue_saturation_value_p: 0.3
hue_shift_limit: 10
sat_shift_limit: 15
val_shift_limit: 10
gaussian_blur_p: 0.1
gaussian_blur_limit: 3
coarse_dropout_p: 0.2
min_holes: 1
max_holes: 8
max_height: 24
max_width: 24
