backbone: efficientnet_b0
pretrained: true
dropout: 0.2
num_classes: ${data.dataset.num_classes}
freeze_backbone: false
# If set, unfreeze all params starting from this epoch (0-based).
unfreeze_epoch: null
